### ISSUE TITLE
Đanh học lodash

### ISSUE THREAD

**Issue by dattengichaduoc** [nodeschool/hanoi#12]
Thấy cũng dễ cần nhận dịch luôn (" english hơi ngu , dịch xong review giùm em ")

lololodash ( bài nhân )

**Comment by dominhhai** [comment]
:+1:  OK em, em gửi link fork của em qua đây luôn nhé :)

**Comment by dattengichaduoc** [comment]
Em dau co link fork gi dau . :D em van chua biet dich ntn
