### ISSUE TITLE
Logo/Sticker

### ISSUE THREAD

**Issue by dominhhai** [nodeschool/hanoi#2]
Cần thiết kế logo cho Hà Nội.
Không biết mọi người có ý tưởng gì không?
### Hướng dẫn

Mã của Hanoi: HAN

Ta có thể [sử dụng file .AI/.SVG mẫu](https://github.com/nodeschool/nodeschool.github.io/tree/master/images/make-a-sticker) để thiết kế cho khớp với mẫu chung của cả dự án. Anh Finn còn tạo 1 trang cho phép thay đổi được màu cho logo ở [đây](http://www.finnpauls.de/nodeschool-stickerify/).
### Logo của một số chapter khác:

http://nodeschool.io/hexdex.html

![Logo](http://nodeschool.io/international-day/chapters.png)

**Comment by dominhhai** [comment]
Chưa biết chọn mẫu nào :girl: 

![11180461_944123238952570_676092147_o](https://cloud.githubusercontent.com/assets/1484298/7244520/bb448260-e817-11e4-9b76-5283e908e455.jpg)

**Comment by thinhit** [comment]
:100:  e thấy cái thứ 3 được đấy bác

**Comment by dominhhai** [comment]
Mình cũng thích cái thứ 3, thứ 2. 2 cái này màu sáng nên khi dán vào máy tính dù màu trắng, hay đen đi chăng nữa cũng nổi.

**Comment by hainh** [comment]
vote cho 3 nhé

**Comment by minatu2d** [comment]
Số 1

**Comment by dominhhai** [comment]
1. File AI
   https://github.com/nodeschool/hanoi/blob/master/logo/logohan.ai
2. File SVG
   https://github.com/nodeschool/hanoi/blob/master/logo/logohan.svg
3. File PNG
   https://github.com/nodeschool/hanoi/blob/master/logo/logohan.png

**Comment by ngnam** [comment]
vote 3 nhe
