### ISSUE TITLE
Danh sách tham gia buổi 1

### ISSUE THREAD

**Issue by dominhhai** [nodeschool/hanoi#8]
Theo kiến nghị của bạn @bigtheory mình sẽ thêm một mục các bạn tham gia event tại github.
Vì chưa hỏi ý kiến của các bạn nên mình sẽ không đưa thông tin cụ thể của các bạn tham gia.
1. Trần Hữu Thiện
2. Nguyễn Anh Tuấn
3. Phạm Trần Huỳnh
4. Kiên
5. Nguyễn Duy Đức
6. hungba
7. Cao Manh Dat
8. Tran Viet
9. Đinh Công Quân
10. Phạm Văn Quân
11. Do Dang Duy
12. Nguyễn Trung Kiên
13. Phạm Tuấn Khanh
14. Đàm Việt Anh
15. ホアン ゴック クイ
16. Hoàng Ngọc Quý
17. nguyễn thành công
18. Đỗ Đức Hiếu
19. Cong Tran
20. Bùi Xuân Quý

**Comment by lephuhai** [comment]
Buổi 1 mọi người tham gia có đủ không anh @dominhhai

**Comment by dominhhai** [comment]
Gần 1 nửa các bạn được join thì không đi.
Một số bạn báo không nhận được email nhắc và lại còn quên nữa.

**Comment by lephuhai** [comment]
Em quên chưa nhắc anh để ý chuyện các bạn trong danh sách cần phải confirm là tham dự được. Em thấy ảnh mọi người đi buổi 1 không được như mong muốn. Mà danh sách wait list vẫn còn nhiều :8ball:

**Comment by dominhhai** [comment]
ừ, cái này mình sẽ rút kinh nghiệm. Có nhiều bạn wail list gửi mail lại cho mình bảo muốn đi thì giờ làm thế nào. Chắc phần nào đó các bạn biết nhiều người sẽ không đi, vậy mà mình lại không biết. Rút kinh nghiệm. Cám ơn @bigtheory nhé.

**Comment by lephuhai** [comment]
Các anh tổ chức những buổi meetup như thế này thì chi phí đều do ban tổ chức chi trả hết để mọi người có thể tham gia học tập miễn phí. Em nghĩ vẫn nên duy trì một khoản chi phí nhỏ để chi tiêu cho các buổi gặp mặt, ngoài việc tổ chức ở phòng có máy chiếu, sao không có những lịch offline ạ :)

**Comment by dominhhai** [comment]
@bigtheory Lần tới bạn đi thử 1 lần rồi sẽ thấy thế nào :+1: 
Bọn mình gắng vào được đầu tháng 6. Cũng đang tính phương án xin tài trợ, vẫn muốn các bạn học viên được tham dự free ở các buổi gặp mặt hàng tháng. Còn các event đặc biệt thì có thể cần mua vé nếu khoản tài trợ không đủ.

**Comment by lephuhai** [comment]
Vâng ạ. Chắc chắn lần sau em sẽ có mặt :)
